### ISSUE TITLE
TS typings aren't exported correctly

### ISSUE THREAD

**Issue by inglec-arista** [rufman/ts-rws#8]
When importing from `ts-rws`, the typings cannot be located:
```
Could not find a declaration file for module 'ts-rws'.
```

`package.json` defines the types location as follows:
```json
"typings": "typings/index.d.ts",
```

However, the `typings` directory does not contain `index.d.ts`, just `src` and `test` directories.

**Comment by rufman** [comment]
fixed here: #9
